try

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -15,25 +15,23 @@ while read -r line; do
 done <<<"$files"
 
 for hook in "${hooks[@]}"; do
-    hook_name=$(basename "$hook")
+	hook_name=$(basename "$hook")
 	for file in "${theArray[@]}"; do
 		full_file="$root/$file"
 		# echo "file=$file"
 		# echo "hook=$hook"
 		# echo "full_file=$full_file"
-        (
-            set -e
-            "$hook" "$full_file"
-        )
-        error_code=$?
-        if [ $error_code -ne 0 ]
+		(
+			set -e
+			"$hook" "$full_file"
+		)
+		error_code=$?
+		if [ $error_code -ne 0 ]; then
+			echo "Failed with $hook_name on $file"
 
-        then
-            echo "Failed with $hook_name on $file"
-
-        else
-        echo "OK with $hook_name on $file"
-        fi
+		else
+			echo "OK with $hook_name on $file"
+		fi
 	done
 done
 
