Add check-case-conflict

diff --git a/hooks/basic_hooks b/hooks/basic_hooks
--- a/hooks/basic_hooks
+++ b/hooks/basic_hooks
@@ -6,6 +6,15 @@ process_file() {
 		return 0
 	fi
 
+	# check-case-conflict
+	if ! command -v check-case-conflict >/dev/null 2>&1; then
+		printf "ERROR: check-case-conflict missing\n"
+		return 1
+	fi
+	if ! check-case-conflict "$1"; then
+		printf "ERROR: check-case-conflict failed on %s\n" "$1"
+	fi
+
 	# end-of-file-fixer
 	if ! command -v end-of-file-fixer >/dev/null 2>&1; then
 		printf "ERROR: end-of-file-fixer missing\n"
