Add check-vcs-premalinks

diff --git a/hooks/basic_hooks b/hooks/basic_hooks
--- a/hooks/basic_hooks
+++ b/hooks/basic_hooks
@@ -33,6 +33,15 @@ process_file() {
 		printf "ERROR: check-merge-conflict failed on %s\n" "$1"
 	fi
 
+	# check-vcs-permalinks
+	if ! command -v check-vcs-permalinks >/dev/null 2>&1; then
+		printf "ERROR: check-vcs-permalinks missing\n"
+		return 1
+	fi
+	if ! check-vcs-permalinks "$1"; then
+		printf "ERROR: check-vcs-permalinks failed on %s\n" "$1"
+	fi
+
 	# end-of-file-fixer
 	if ! command -v end-of-file-fixer >/dev/null 2>&1; then
 		printf "ERROR: end-of-file-fixer missing\n"
