Add more hooks

diff --git a/hooks/basic_hooks b/hooks/basic_hooks
--- a/hooks/basic_hooks
+++ b/hooks/basic_hooks
@@ -15,6 +15,24 @@ process_file() {
 		printf "ERROR: check-case-conflict failed on %s\n" "$1"
 	fi
 
+	# check-executables-have-shebangs
+	if ! command -v check-executables-have-shebangs >/dev/null 2>&1; then
+		printf "ERROR: check-executables-have-shebangs missing\n"
+		return 1
+	fi
+	if ! check-executables-have-shebangs "$1"; then
+		printf "ERROR: check-executables-have-shebangs failed on %s\n" "$1"
+	fi
+
+	# check-merge-conflict
+	if ! command -v check-merge-conflict >/dev/null 2>&1; then
+		printf "ERROR: check-merge-conflict missing\n"
+		return 1
+	fi
+	if ! check-merge-conflict "$1"; then
+		printf "ERROR: check-merge-conflict failed on %s\n" "$1"
+	fi
+
 	# end-of-file-fixer
 	if ! command -v end-of-file-fixer >/dev/null 2>&1; then
 		printf "ERROR: end-of-file-fixer missing\n"
