WIP, mostly ok

diff --git a/hooks/check_python b/hooks/check_python
--- a/hooks/check_python
+++ b/hooks/check_python
@@ -54,6 +54,19 @@ process_file() {
 		return 1
 	fi
 
+	## reorder-python-imports
+	if ! command -v reorder-python-imports >/dev/null 2>&1; then
+		printf "ERROR: reorder-python-imports missing\n"
+		return 1
+	fi
+	if ! reorder-python-imports --exit-zero-even-if-changed --py38-plus "$1" >/dev/null 2>&1; then
+		printf "ERROR: reorder-python-imports failed on %s\n" "$1"
+	fi
+	if ! black "$1" --quiet; then
+		printf "ERROR: black (after reorder-python-imports) failed on %s\n" "$1"
+		return 1
+	fi
+
 	## yesqa
 	if ! command -v yesqa >/dev/null 2>&1; then
 		printf "ERROR: yesqa missing\n"
@@ -75,16 +88,14 @@ process_file() {
 		printf "ERROR: flake8 missing\n"
 		return 1
 	fi
-	path_ignores="$(dirname "$(dirname "${BASH_SOURCE[0]}")")/python/flake8-ignores"
-	declare -a all_ignores
+	path_args="$(dirname "$(dirname "${BASH_SOURCE[0]}")")/python/flake8"
+	declare -a all_args
 	while read -r line; do
-		if [ -n "$line" ] && ! [[ "$line" == \#* ]]; then
-			all_ignores+=("$line")
+		if [ -n "$line" ] && ! [[ "$line" == *\#* ]]; then
+			all_args+=("$line")
 		fi
-	done <"$path_ignores"
-	ignore=$(printf ",%s" "${all_ignores[@]}")
-	ignore=${ignore:1}
-	if ! flake8 --ignore="$ignore" --per-file-ignores="tests/*.py:S101" "$1"; then
+	done <"$path_args"
+	if ! flake8 "${all_args[@]}" "$1"; then
 		printf "ERROR: flake8 failed on %s\n" "$1"
 		return 1
 	fi
