Always "git add" after black (#18)
* Do git add after black&shfmt

* Always add after black is OK

diff --git a/hooks/check_shell b/hooks/check_shell
--- a/hooks/check_shell
+++ b/hooks/check_shell
@@ -9,17 +9,21 @@ process_file() {
 		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt missing\n"
 		return 1
 	fi
-	if ! shfmt -w "$1"; then
+	if shfmt -w "$1"; then
+		git add "$1"
+	else
 		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt failed on %s\n" "$1"
 		return 1
 	fi
-	git add "$1"
 	if ! command -v shellcheck >/dev/null 2>&1; then
 		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shellcheck missing\n"
 		return 1
 	fi
-	shellcheck "$1"
-	return $?
+	if ! shellcheck "$1"; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shellcheck failed on %s\n" "$1"
+		return 1
+	fi
+	return 0
 }
 
 is_bash_file() {
