Do git add after black&shfmt

diff --git a/hooks/check_python b/hooks/check_python
--- a/hooks/check_python
+++ b/hooks/check_python
@@ -9,7 +9,11 @@ process_file() {
 		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: black missing\n"
 		return 1
 	fi
-	black "$1"
+	if ! black "$1"; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: black failed on %s\n" "$1"
+		return 1
+	fi
+	git add "$1"
 	return $?
 }
 
