Add requirements.txt

diff --git a/hooks/check_python b/hooks/check_python
--- a/hooks/check_python
+++ b/hooks/check_python
@@ -7,6 +7,16 @@ process_file() {
 	fi
 
 	# formatters
+	if ! command -v add-trailing-comma >/dev/null 2>&1; then
+		printf "ERROR: add-trailing-comma missing\n"
+		return 1
+	fi
+	if add-trailing-comma "$1" --py36-plus; then
+		git add "$1"
+	else
+		printf "ERROR: add-trailing-comma failed on %s\n" "$1"
+		return 1
+	fi
 	if ! command -v black >/dev/null 2>&1; then
 		printf "ERROR: black missing\n"
 		return 1
