Make black quiet, add flake8

diff --git a/hooks/check_python b/hooks/check_python
--- a/hooks/check_python
+++ b/hooks/check_python
@@ -5,14 +5,26 @@ process_file() {
 		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "check_python skipped %s\n" "$1"
 		return 0
 	fi
+
+	# formatters
 	if ! command -v black >/dev/null 2>&1; then
 		printf "ERROR: black missing\n"
 		return 1
 	fi
-	if black "$1"; then
+	if black "$1" --quiet; then
 		git add "$1"
 	else
 		printf "ERROR: black failed on %s\n" "$1"
+		return 1
+	fi
+
+	# linters
+	if ! command -v flake8 >/dev/null 2>&1; then
+		printf "ERROR: flake8 missing\n"
+		return 1
+	fi
+	if ! flake8 "$1"; then
+		printf "ERROR: flake8 failed on %s\n" "$1"
 		return 1
 	fi
 	return 0
