pre-commit will break down hooks & files

diff --git a/hooks/check_shell b/hooks/check_shell
--- a/hooks/check_shell
+++ b/hooks/check_shell
@@ -14,10 +14,30 @@ process_files() {
 	return $code
 }
 
-is_bash_file() {
-	if ! [ -f "$1" ]; then
+
+process_file() {
+	if ! is_bash_file; then
+			[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "SKIP: check_shell skipping %s\n" "$1"
+			return 0
+	fi
+	if ! command -v shfmt >/dev/null 2>&1; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt missing\n"
 		return 1
 	fi
+	if ! shfmt -w "$1"; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt failed on %s\n" "$1"
+	fi
+	git add "$1"
+	if ! command -v shellcheck >/dev/null 2>&1; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shellcheck missing\n"
+		return 1
+	fi
+	shellcheck "$1"
+	return $?
+}
+
+
+is_bash_file() {
 	if [[ "$1" == *.bash ]]; then
 		return 0
 	fi
@@ -29,22 +49,7 @@ is_bash_file() {
 	fi
 }
 
-process_file() {
-	if ! command -v shfmt >/dev/null 2>&1; then
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt missing\n"
-		return 1
-	fi
-	if ! shfmt -w "$file"; then
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt failed on %s\n" "$file"
-	fi
-	git add "$file"
-	if ! command -v shellcheck >/dev/null 2>&1; then
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shellcheck missing\n"
-		return 1
-	fi
-	shellcheck "$file"
-	return $?
-}
 
-process_files "$@"
+
+process_file "$1"
 exit $?
