Use regex

diff --git a/hooks/prettier b/hooks/prettier
--- a/hooks/prettier
+++ b/hooks/prettier
@@ -7,25 +7,24 @@ process_file() {
 	fi
 
 	# fixers
-	# if ! command -v shfmt >/dev/null 2>&1; then
-	# 	printf "ERROR: shfmt missing\n"
-	# 	return 1
-	# fi
-	# if ! shfmt -w "$1"; then
-	# 	printf "ERROR: shfmt failed on %s\n" "$1"
-	# 	return 1
-	# fi
+	if ! command -v npx >/dev/null 2>&1; then
+		printf "ERROR: npx missing\n"
+		return 1
+	fi
+	if ! npx prettier --write "$1"; then
+		printf "ERROR: prettier failed on %s\n" "$1"
+		return 1
+	fi
 
 	# fixers - end
 	git add "$1"
 
-	echo "$1..."
 
 	return 0
 }
 
 is_accepted_file() {
-	if [[ -f "$1" ]] && [[ "$1" =~ \.(html|js|md|ts)$ ]]; then
+	if [[ "$1" =~ \.(html|js|json|md|tomj|ts|xml)$ ]]; then
 		return 0
 	else
 		return 1
