Add basic hooks

diff --git a/hooks/python_hooks b/hooks/python_hooks
--- a/hooks/python_hooks
+++ b/hooks/python_hooks
@@ -12,7 +12,7 @@ process_file() {
 		printf "ERROR: black missing\n"
 		return 1
 	fi
-	if ! black "$1" --quiet; then
+	if ! black --quiet "$1"; then
 		printf "ERROR: black failed on %s\n" "$1"
 		return 1
 	fi
@@ -22,10 +22,10 @@ process_file() {
 		printf "ERROR: add-trailing-comma missing\n"
 		return 1
 	fi
-	if ! add-trailing-comma "$1" --exit-zero-even-if-changed --py36-plus; then
-		printf "ERROR: failed on %s\n" "$1"
+	if ! add-trailing-comma --exit-zero-even-if-changed --py36-plus "$1"; then
+		printf "ERROR: add-trailing-comma failed on %s\n" "$1"
 	fi
-	if ! black "$1" --quiet; then
+	if ! black --quiet "$1"; then
 		printf "ERROR: black (after add-trailing-comma) failed on %s\n" "$1"
 		return 1
 	fi
@@ -36,7 +36,7 @@ process_file() {
 		return 1
 	fi
 	autoflake --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables "$1"
-	if ! black "$1" --quiet; then
+	if ! black --quiet "$1"; then
 		printf "ERROR: black (after autoflake) failed on %s\n" "$1"
 		return 1
 	fi
@@ -49,7 +49,7 @@ process_file() {
 	if ! pyupgrade --exit-zero-even-if-changed --py38-plus "$1"; then
 		printf "ERROR: pyupgrade failed on %s\n" "$1"
 	fi
-	if ! black "$1" --quiet; then
+	if ! black --quiet "$1"; then
 		printf "ERROR: black (after pyupgrade) failed on %s\n" "$1"
 		return 1
 	fi
@@ -62,7 +62,7 @@ process_file() {
 	if ! reorder-python-imports --exit-zero-even-if-changed --py38-plus "$1" >/dev/null 2>&1; then
 		printf "ERROR: reorder-python-imports failed on %s\n" "$1"
 	fi
-	if ! black "$1" --quiet; then
+	if ! black --quiet "$1"; then
 		printf "ERROR: black (after reorder-python-imports) failed on %s\n" "$1"
 		return 1
 	fi
@@ -75,7 +75,7 @@ process_file() {
 	if ! yesqa "$1" >/dev/null 2>&1; then
 		printf "ERROR: yesqa failed on %s\n" "$1"
 	fi
-	if ! black "$1" --quiet; then
+	if ! black --quiet "$1"; then
 		printf "ERROR: black (after yesqa) failed on %s\n" "$1"
 		return 1
 	fi
