Add pytest

diff --git a/hooks/python_hooks b/hooks/python_hooks
--- a/hooks/python_hooks
+++ b/hooks/python_hooks
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 process_file() {
-	if ! is_python_file "$1"; then
+	if ! [[ "$1" =~ \.(py)$ ]]; then
 		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "python_hooks skipped %s\n" "$1"
 		return 0
 	fi
@@ -108,16 +108,21 @@ process_file() {
 	# linters - end
 
 	# tests
-
-	return 0
-}
-
-is_python_file() {
-	if [[ "$1" =~ \.(py)$ ]]; then
+	if ! [[ "$1" =~ ^test_ ]]; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "pytest skipped %s\n" "$1"
 		return 0
-	else
+	fi
+	if ! command -v pytest >/dev/null 2>&1; then
+		printf "ERROR: pytest missing\n"
 		return 1
 	fi
+	if ! pytest "$1"; then
+		printf "ERROR: pytest failed on %s\n" "$1"
+		return 1
+	fi
+
+	# tests - end
+	return 0
 }
 
 process_file "$1"
