Merge into check_shell

diff --git a/hooks/run_black b/hooks/run_black
--- a/hooks/run_black
+++ b/hooks/run_black
@@ -4,19 +4,20 @@ utilities="$(dirname "$(dirname "$(readlink -f "$0")")")/utilities"
 PATH="${PATH:+${PATH}:}$utilities"
 
 run_hook() {
-	if ! has_command shellcheck; then
+	if ! has_command black; then
 		return 1
 	fi
 
 	code=0
 	for file in "$@"; do
-		if is_bash_file "$file"; then
-			if ! shellcheck "$file"; then
-				[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "shellcheck failed %s\n" "$1"
+		if is_python_file "$file"; then
+			if ! shfmt -w "$file" >/dev/null 2>&1; then
+				[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "shfmt failed %s\n" "$1"
 				code=1
 			fi
+			git add "$file"
 		else
-			[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "shellcheck skipped %s\n" "$file"
+			[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "shfmt skipped %s\n" "$file"
 		fi
 	done
 	return $code
