WIP

diff --git a/hooks/shfmt-and-shellcheck b/hooks/shfmt-and-shellcheck
--- a/hooks/shfmt-and-shellcheck
+++ b/hooks/shfmt-and-shellcheck
@@ -13,23 +13,27 @@ needs_run() {
 }
 
 run_hook() {
+	debug="$PRE_COMMIT_DEBUG"
 	if ! needs_run "$1"; then
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Skipping shfmt/shellcheck %s\n" "$1"
+		[[ -n "$debug" ]] && printf "Skipping shfmt/shellcheck %s\n" "$1"
 		return 0
 	fi
 
-	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Running shfmt %s\n" "$1"
-	if ! shfmt -w "$1"; then
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Failing shfmt %s\n" "$1"
-		return 1
-	fi
-	git add "$1"
-	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Running shellcheck %s\n" "$1"
-	if shellcheck "$1"; then
-		return 0
-	else
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Failing shellcheck %s\n" "$1"
-		return 1
+	if command -v shfmt >/dev/null 2>&1 
+	then
+		[[ -n "$debug" ]] && printf "Running shfmt %s\n" "$1"
+		if ! shfmt -w "$1"; then
+			[[ -n "$debug" ]] && printf "Failing shfmt %s\n" "$1"
+			return 1
+		fi
+		git add "$1"
+		[[ -n "$debug" ]] && printf "Running shellcheck %s\n" "$1"
+		if shellcheck "$1"; then
+			return 0
+		else
+			[[ -n "$debug" ]] && printf "Failing shellcheck %s\n" "$1"
+			return 1
+		fi
 	fi
 }
 
