Correctly run hook

diff --git a/hooks/shfmt-and-shellcheck b/hooks/shfmt-and-shellcheck
--- a/hooks/shfmt-and-shellcheck
+++ b/hooks/shfmt-and-shellcheck
@@ -8,25 +8,32 @@ needs_run() {
 	if [[ "$line" == *bash* ]]; then
 		return 0
 	else
-		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "shfmt/shellcheck !=> %s\n" "$1"
 		return 1
 	fi
 }
 
 run_hook() {
-	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "shfmt             => %s\n" "$1"
+	if ! needs_run "$1"; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Skipping shfmt/shellcheck %s\n" "$1"
+		return 0
+	fi
+
+	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Running shfmt %s\n" "$1"
 	if ! shfmt -w "$1"; then
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Failing shfmt %s\n" "$1"
 		return 1
 	fi
 	git add "$1"
-	if [ -n "$PRE_COMMIT_DEBUG" ]; then
-		printf "shellcheck        => %s\n" "$1"
+	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Running shellcheck %s\n" "$1"
+	if shellcheck "$1"; then
+		return 0
+	else
+		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Failing shellcheck %s\n" "$1"
+		return 1
 	fi
-	shellcheck "$1"
-	return $?
 }
 
-if needs_run "$1" && run_hook "$1"; then
+if run_hook "$1"; then
 	exit 0
 else
 	exit 1
